on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        perl: [ '5.32', '5.30.1', '5.16.3', '5.12.3' ]
    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - run: perl -V
    - run: cpanm --installdeps .
    - run: prove -lv t
