on:
  push:
    branches:
      - master


# perl: [ '5.32', '5.30', '5.28' ]
# perl: [ '5.32', '5.30.1', '5.16.3', '5.12.3' ]
# os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
# https://github.com/marketplace/actions/setup-perl-environment
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.16.3' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: env
      - id:  install-cpanm
        run: |
          curl -L https://cpanmin.us | perl - App::cpanminus
          # installs to something like /home/runner/.cpanm/work/1600962463.2588/App-cpanminus-1.7044/bin/cpanm
          #curl -L https://cpanmin.us | perl - --sudo App::cpanminus
          #find /bin /usr/ $HOME $GITHUB_WORKSPACE -name cpanm | xargs ls -lht
          #find /bin /usr/ $HOME $GITHUB_WORKSPACE -name cpanm -exec {} --version \;
          which cpanm
          CPANMPATH=$(which cpanm)
          find $HOME/.cpanm -type f -executable -name cpanm | xargs -P 1 -n 1 bash -c ' echo "dir of $0" >&2; dirname $0 ' | tee $HOME/CPANMDIRs.txt
          for path in $(cat $HOME/CPANMDIRs.txt); do echo "Added $path"; export PATH=$path:$PATH; done
          echo $PATH
          which cpanm
          exit 1 # stop here for now
      - id:  cpanm
        run: |
          export PERL5LIB=$PERL5LIB:$HOME/lib/perl5
          export PATH=$PATH:/usr/local/bin
          which cpanm
          echo "CPANM - start"
          cpanm -l $HOME --installdeps --verbose --force .
          echo "CPANM - done"
          echo "CPANM - start direct installation of File::Which"
          cpanm -l $HOME File::Which --force --notest
          echo "CPANM - done"
          locate Which.pm || true
          find $HOME -name Which.pm || true
          perl -MFile::Which -MData::Dumper -e 'print Dumper \%INC'
      - id: prove-lv-t
        run: |
          export PERL5LIB=$PERL5LIB:$HOME/lib/perl5
          prove -lv t
