on:
  push:
    branches:
      - master


# perl: [ '5.32', '5.30', '5.28' ]
# perl: [ '5.32', '5.30.1', '5.16.3', '5.12.3' ]
# os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
# https://github.com/marketplace/actions/setup-perl-environment
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.16.3' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - id:  cpanm
        run: |
          cd $GITHUB_WORKSPACE
          cpanm -l . --installdeps --verbose .
          perl -MFile::Which -MData::Dumper -e 'print Dumper \%INC' || true
      - id: prove-lv-t
        run: |
          export PERL5LIB=$PERL5LIB:$GITHUB_WORKSPACE/lib/perl5
          echo $PERL5LIB
          locate Which.pm || true
          find $GITHUB_WORKSPACE -name Which.pm || true
          prove -lv t
