on:
  push:
    branches:
      - master


# perl: [ '5.32', '5.30', '5.28' ]
# perl: [ '5.32', '5.30.1', '5.16.3', '5.12.3' ]
# os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
# https://github.com/marketplace/actions/setup-perl-environment
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        #perl: [ '5.16.3' ]
        perl: [ '5.32', '5.30.1', '5.16.3' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: env
        run:  env
      - name: perl-dependencies
        run:  |
          export PERL5LIB=$PERL5LIB:$HOME/lib/perl5
          which cpanm
          #cpanm --verbose --notest --force ExtUtils::MakeMaker
          cpanm -l $HOME --installdeps --verbose --notest --force .
          perl Makefile.PL
          perl -MFile::Which -MData::Dumper -MSpreadsheet::XLSX -MArray::IntSpan -e 'print Dumper \%INC'
          make
          echo; echo; echo;
          cat MYMETA.json
      - id: prove-lv-t
        run: |
          export PERL5LIB=$PERL5LIB:$HOME/lib/perl5
          prove -lv t
